Added feed status component
nordnet/nordnet-component-kit pull request #442
Opened 2017-01-09 16:39 UTC by robineng

2017-01-10 11:24 UTC, robineng commented
Related to #198

2017-01-11 09:01 UTC, bstream requested changes
Please see the comments below 🚀

2017-01-11 09:01 UTC, bstream commented on src/components/freshness-indicator/freshness-indicator-tooltip-delay-content.jsx
> +    <span key={key} >{time[key]} <FormattedMessage {...messages[key]} /> </span>
My hunch is that **3h 5m 23s** is better than **3 h 5 m 23 s**

2017-01-11 09:01 UTC, bstream commented on src/components/freshness-indicator/freshness-indicator-tooltip-delay-content.jsx
> +  isActive: {
`isActive` -> `notActive`

2017-01-11 09:01 UTC, bstream commented on src/components/freshness-indicator/freshness-indicator-tooltip-delay-content.jsx
> +export default FreshnessIndicatorTooltipDelayContent;
Maybe change `FreshnessIndicatorTooltipDelayContent` to `TooltipDelayContent`?

2017-01-11 09:01 UTC, bstream commented on src/components/freshness-indicator/freshness-indicator-tooltip-delay.jsx
> +function FreshnessIndicatorTooltipDelay(props) {
Maybe remove FreshnessIndicator from this component name?

2017-01-11 09:01 UTC, bstream commented on src/components/freshness-indicator/freshness-indicator-tooltip-timestamp.jsx
> +function FreshnessIndicatorTooltipTimestamp({ timestamp }) {
See comment on FreshnessIndicatorTooltipDelay

2017-01-11 09:01 UTC, bstream commented on src/components/freshness-indicator/freshness-indicator-tooltip-timestamp.jsx
> +    return (<div />);
`return null`

2017-01-11 09:01 UTC, bstream commented on src/components/freshness-indicator/freshness-indicator-tooltip-timestamp.jsx
> +      <b><FormattedMessage {...messages.updated} />: <DateTime value={new Date(timestamp)} format="numeric" type="time" /></b>
You should be able to omit `new Date()` from the value and instead pass `value={timestamp}`.

2017-01-11 09:01 UTC, bstream commented on src/components/freshness-indicator/freshness-indicator.examples.md
> +COMPONENT_KIT.FRESHNESS_INDICATOR.IS_ACTIVE | Close price
Don't forget to update key

2017-01-11 09:01 UTC, bstream commented on src/components/freshness-indicator/freshness-indicator.examples.md
> +No delay feed:
delay*ed data*?

2017-01-11 09:01 UTC, bstream commented on src/components/freshness-indicator/freshness-indicator.examples.md
> +Delay feed:
`**Delayed data:**`

2017-01-11 09:01 UTC, bstream commented on src/components/freshness-indicator/freshness-indicator.jsx
> +function getIconType(delay, isActive) {
export and test separately

2017-01-11 09:01 UTC, bstream commented on src/components/freshness-indicator/freshness-indicator.jsx
> +function getColor(isActive) {
export and test separately

2017-01-11 09:01 UTC, bstream commented on test/components/freshness-indicator/freshness-indicator-tooptip-delay-content.test.js
> +  it('should render DELAY message if isActive is larger than 1 and isActive is false', () => {
`should render DELAY message if isActive is larger than 1 and isActive is false` -> `should render DELAY message if delay is larger than 1 and isActive is false`

2017-01-11 10:09 UTC, bstream approved these changes

2017-01-11 10:09 UTC, bstream commented
Well done 🙏

2017-01-11 10:11 UTC, merged