Added category of components List Components and added component BasicList
nordnet/nordnet-component-kit pull request #555
Opened 2017-03-21 15:46 UTC by johankitti

2017-03-22 15:24 UTC, johankitti commented
![screen shot 2017-03-22 at 16 23 59](https://cloud.githubusercontent.com/assets/7893211/24205555/ffd57894-0f1b-11e7-996f-701dadeb5c69.png)

2017-03-22 16:21 UTC, iamstarkov reviewed
why did you remove yarn lock?

2017-03-22 16:45 UTC, johankitti commented
I might have misinterpreted Andreas, but he told me to remove it.

2017-03-23 07:43 UTC, bstream commented on src/components/icon-list-row/row-info.jsx
> +      {children[0]}
This seems a bit odd imo. Either we should force it to _exactly_ two "child components" by not using the `children` prop or we should accept any number of children.

2017-03-23 08:52 UTC, JohnPhoto commented on src/components/basic-list/basic-list.jsx
> +    <div>
Why not UL with LI's? (which is the semantic way of saying "this is a list".)

2017-03-23 08:52 UTC, JohnPhoto commented on src/components/icon-list-row/row-info.jsx
> +    <div style={styles}>
Row's should be LI's for semantics.

2017-03-23 08:55 UTC, JohnPhoto commented
@iamstarkov yarn.lock file was coupled with our internal registry and it was not possible to build this out in the wild (a.k.a. Travis). 
@johankitti Another solution would be to reset the registry-setting and recommit it.

2017-04-07 08:29 UTC, bstream requested changes

2017-04-07 08:29 UTC, bstream commented on src/components/icon-row/icon-row.jsx
> +import { TextIcon } from 'nordnet-ui-kit';
Now `Avatar`, and it only exists in the latest beta 6

2017-04-07 08:29 UTC, bstream commented on src/components/icon-row/icon-row.examples.md
> +            textIconText={account.type}
hmm, should probably rename this and maybe not depend on TextIcon / Avatar at all in here so that we can change it for flags and other items later?

2017-04-07 08:29 UTC, bstream commented on src/components/icon-row/icon-row.jsx
> +  infoPaddingLeft,
Can change these 4 lines to infoStyles (containing paddingLeft, paddingRight, marginRight, marginLeft)

2017-04-07 08:29 UTC, bstream commented on src/components/icon-row/row-info.jsx
> +  bottom: PropTypes.bool,
What is this prop for? Should have a more descriptive name if possible :)

2017-04-07 08:34 UTC, bstream commented on src/components/icon-row/icon-row.jsx
> +  iconComponent: PropTypes.node,
Can remove Component from the name here

2017-04-07 08:35 UTC, bstream commented on src/components/icon-row/row-info.jsx
> +  leftItem: null,
Remove `null` from defaultProps. They are obsolete

2017-04-07 08:35 UTC, bstream commented on src/components/icon-row/icon-row.jsx
> +  iconComponent: null,
Remove `null` from defaultProps. They are obsolete

2017-04-10 11:34 UTC, bstream approved these changes

2017-04-10 11:34 UTC, merged